//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hspi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hspi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;active-app&gt;
        ///    &lt;app&gt;Roku&lt;/app&gt;
        ///&lt;/active-app&gt;.
        /// </summary>
        internal static string ActiveAppTemplate {
            get {
                return ResourceManager.GetString("ActiveAppTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;apps&gt;
        ///    &lt;app id=&quot;1&quot; version=&quot;1.0.0&quot;&gt;Emulated App 1&lt;/app&gt;
        ///    &lt;app id=&quot;2&quot; version=&quot;1.0.0&quot;&gt;Emulated App 2&lt;/app&gt;
        ///    &lt;app id=&quot;3&quot; version=&quot;1.0.0&quot;&gt;Emulated App 3&lt;/app&gt;
        ///    &lt;app id=&quot;4&quot; version=&quot;1.0.0&quot;&gt;Emulated App 4&lt;/app&gt;
        ///    &lt;app id=&quot;5&quot; version=&quot;1.0.0&quot;&gt;Emulated App 5&lt;/app&gt;
        ///    &lt;app id=&quot;6&quot; version=&quot;1.0.0&quot;&gt;Emulated App 6&lt;/app&gt;
        ///    &lt;app id=&quot;7&quot; version=&quot;1.0.0&quot;&gt;Emulated App 7&lt;/app&gt;
        ///    &lt;app id=&quot;8&quot; version=&quot;1.0.0&quot;&gt;Emulated App 8&lt;/app&gt;
        ///    &lt;app id=&quot;9&quot; version=&quot;1.0.0&quot;&gt;Emulated App 9&lt;/app&gt;
        ///    &lt;app id=&quot;10&quot; v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppsTemplate {
            get {
                return ResourceManager.GetString("AppsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;device-info&gt;
        ///    &lt;udn&gt;{0}&lt;/udn&gt;
        ///    &lt;serial-number&gt;{1}&lt;/serial-number&gt;
        ///    &lt;device-id&gt;{1}&lt;/device-id&gt;
        ///    &lt;vendor-name&gt;Roku&lt;/vendor-name&gt;
        ///    &lt;model-number&gt;4400X&lt;/model-number&gt;
        ///    &lt;model-name&gt;Roku 4&lt;/model-name&gt;
        ///    &lt;model-region&gt;US&lt;/model-region&gt;
        ///    &lt;supports-ethernet&gt;true&lt;/supports-ethernet&gt;
        ///    &lt;wifi-mac&gt;00:00:00:00:00:00&lt;/wifi-mac&gt;
        ///    &lt;ethernet-mac&gt;00:00:00:00:00:00&lt;/ethernet-mac&gt;
        ///    &lt;network-type&gt;ethernet&lt;/network-type&gt;
        ///    &lt;user-device-name&gt;{2}&lt;/user-device-name&gt;
        ///    &lt;software-versio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeviceInfoTemplate {
            get {
                return ResourceManager.GetString("DeviceInfoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAoMBgDTD2qgAAAAASUVORK5CYII=.
        /// </summary>
        internal static string IconBase64 {
            get {
                return ResourceManager.GetString("IconBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;device&gt;
        ///    &lt;deviceType&gt;urn:roku-com:device:player:1-0&lt;/deviceType&gt;
        ///    &lt;friendlyName&gt;{0}&lt;/friendlyName&gt;
        ///    &lt;manufacturer&gt;Roku&lt;/manufacturer&gt;
        ///    &lt;manufacturerURL&gt;http://www.roku.com/&lt;/manufacturerURL&gt;
        ///    &lt;modelDescription&gt;Emulated Roku&lt;/modelDescription&gt;
        ///    &lt;modelName&gt;Roku 4&lt;/modelName&gt;
        ///    &lt;modelNumber&gt;4400x&lt;/modelNumber&gt;
        ///    &lt;modelURL&gt;http://www.roku.com/&lt;/modelURL&gt;
        ///    &lt;serialNumber&gt;{1}&lt;/serialNumber&gt;
        ///    &lt;UDN&gt;uuid:{2}&lt;/UDN&gt;
        ///&lt;/device&gt;.
        /// </summary>
        internal static string SsdpDeviceInfoTemplate {
            get {
                return ResourceManager.GetString("SsdpDeviceInfoTemplate", resourceCulture);
            }
        }
    }
}
